"""GitHub issue creation side effect and Markdown body formatter."""
from __future__ import annotations

import os
import json
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import urllib.request

from backend.omium_tracing import trace_tool


# ── Formatter (no network I/O) ────────────────────────────────────────────────

_SEVERITY_LABELS: Dict[str, List[str]] = {
    "critical": ["severity:critical", "sentinelops", "incident", "priority:p0"],
    "high":     ["severity:high",     "sentinelops", "incident", "priority:p1"],
    "medium":   ["severity:medium",   "sentinelops", "incident", "priority:p2"],
    "low":      ["severity:low",      "sentinelops", "incident", "priority:p3"],
}

_ISSUE_TEMPLATE = """\
## 🚨 SentinelOps Autonomous Incident Report

| Field | Value |
|-------|-------|
| **Incident ID** | `{incident_id}` |
| **Service** | `{service}` |
| **Severity** | `{severity}` |
| **Confidence** | {confidence_pct} |
| **Detected At** | {detected_at} |

---

## Root Cause

> {root_cause}

---

## Causal Chain Evidence

```
{causal_chain}
```

---

## Evidence Summary

### 📋 Logs
{logs_summary}

### 🚀 Deployments
{deployment_summary}

---

## Recommended Remediation

**Action:** {remediation_action}

---

## Next Steps

- [ ] Validate the rollback / fix in staging
- [ ] Confirm metrics return to baseline post-action
- [ ] Update runbook with new failure mode
- [ ] Close this issue once resolved

---

*Auto-generated by [SentinelOps AI](https://github.com/sentinelops/sentinelops-ai)*
"""


def format_github_issue(
    service: str,
    severity: str,
    incident_id: str,
    root_cause: str,
    causal_chain: str,
    remediation_action: str,
    confidence_score: float,
    logs_summary: str = "N/A",
    deployment_summary: str = "N/A",
) -> Dict[str, Any]:
    """
    Build a GitHub issue payload dict ``{title, body, labels}``.

    No external calls are made — the dict is ready to pass straight to
    ``create_github_issue``.  Severity is mapped to auto-assigned labels.

    Returns a dict in all cases.
    """
    confidence_pct = f"{confidence_score:.0%}"
    detected_at    = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    labels         = _SEVERITY_LABELS.get(severity.lower(), ["sentinelops", "incident"])

    body = _ISSUE_TEMPLATE.format(
        incident_id=incident_id,
        service=service,
        severity=severity.upper(),
        confidence_pct=confidence_pct,
        detected_at=detected_at,
        root_cause=root_cause,
        causal_chain=causal_chain or "N/A",
        logs_summary=logs_summary,
        deployment_summary=deployment_summary,
        remediation_action=remediation_action,
    )

    return {
        "title":  f"[{severity.upper()}] Incident on {service}: {root_cause[:80]}",
        "body":   body,
        "labels": labels,
    }


# ── Creator (side-effect) ─────────────────────────────────────────────────────

@trace_tool("github.create_issue")
def create_github_issue(
    title: str,
    body: str,
    labels: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """POST a new issue to the configured GitHub repository."""
    token = os.getenv("GITHUB_TOKEN")
    repo  = os.getenv("GITHUB_REPO")  # e.g. owner/repo

    if not token or not repo:
        print(f"[GitHub] (dry-run) Issue: {title}")
        return {
            "ok":      True,
            "dry_run": True,
            "html_url": f"https://github.com/{repo or 'example/repo'}/issues/demo",
            "number":  0,
        }

    url = f"https://api.github.com/repos/{repo}/issues"
    payload = json.dumps({
        "title":  title,
        "body":   body,
        "labels": labels or ["sentinelops", "incident"],
    }).encode()
    req = urllib.request.Request(
        url,
        data=payload,
        headers={
            "Authorization":        f"Bearer {token}",
            "Accept":               "application/vnd.github+json",
            "Content-Type":         "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        data = json.loads(resp.read().decode())
        return {
            "ok":       True,
            "html_url": data.get("html_url"),
            "number":   data.get("number"),
        }
